name: python-starter-qiskit
channels:
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip>=21
  - pip:
      - loguru # required
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==4.2.4
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - cirq-core==0.14.1
      - cirq-google==0.14.1
      - contourpy==1.1.0
      - cryptography==41.0.3
      - cycler==0.11.0
      - dill==0.3.7
      - duet==0.2.9
      - flatbuffers==2.0.7
      - fonttools==4.42.1
      - gast==0.4.0
      - google-api-core==1.21.0
      - google-auth==1.18.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.52.0
      - grpcio==1.57.0
      - h5py==3.9.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - joblib==1.3.2
      - keras==2.7.0
      - Keras-Preprocessing==1.1.2
      - kiwisolver==1.4.4
      - libclang==16.0.6
      - Markdown==3.4.4
      - MarkupSafe==2.1.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - networkx==2.8.8
      - numpy==1.25.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==1.1.5
      - pbr==5.11.1
      - Pillow==10.0.0
      - ply==3.11
      - protobuf==3.17.3
      - psutil==5.9.5
      - pyaml==23.7.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyparsing==3.0.9
      - pyspnego==0.9.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - PyYAML==6.0.1
      - qiskit==0.38.0
      - qiskit-aer==0.11.0
      - qiskit-ibmq-provider==0.19.2
      - qiskit-terra==0.21.2
      - requests==2.31.0
      - requests-ntlm==1.2.0
      - requests-oauthlib==1.3.1
      - retworkx==0.13.1
      - rsa==4.9
      - rustworkx==0.13.1
      - scikit-learn==0.24.1
      - scikit-opt==0.6.3
      - scikit-optimize==0.8.1
      - scipy==1.11.2
      - six==1.16.0
      - sortedcontainers==2.4.0
      - stevedore==5.1.0
      - symengine==0.10.0
      - sympy==1.8
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.7.0
      - tensorflow-estimator==2.7.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorflow-quantum==0.7.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - tweedledum==1.1.1
      - typing_extensions==4.7.1
      - urllib3==1.26.16
      - websocket-client==1.6.1
      - websockets==11.0.3
      - Werkzeug==2.3.7
      - wrapt==1.15.0
      - zipp==3.16.2
variables:
  LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
